### ISSUE TITLE
Random rebuild failures in lens code

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#750]
Once in a while, after merging and calling `make` I get a build error:

```
$ make
dune build --only-packages links,links-postgresql,links-sqlite3 --build-dir=./_build --profile=dev @install
File "core/lens_errors.ml", line 1:
Error: The files core/.links_core.objs/byte/links_core.cmi
       and core/.links_core.objs/byte/links_core__Utility.cmi
       make inconsistent assumptions over interface Links_core
```
Calling `make clean && make` always solves the problem so it is not a big deal, but nevertheless this is not a behaviour I would expect from a build system.

**Comment by dhil** [comment]
I believe this is due to incremental compilation. The interface of utility changes each time we add or remove a thing from there. I am not quite sure why it is always the `lens` module that complains. I suppose it may just be that it is the first thing in the dependency graph...

**Comment by dhil** [comment]
... or it may because `lens` is actually a subpackage, which depends on the interface of the whole `core` package.

**Comment by jstolarek** [comment]
Ok, got it. Thanks!

**Comment by jamescheney** [comment]
Is this actually a bug in the build system that we can fix, or is it addressed by the advice regarding the need to clean and remake when the interface changes?

**Comment by jamescheney** [comment]
I think we should close this, unless there is a specific proposal for improvement besides the "make clean" workaround.

**Comment by dhil** [comment]
I think it is worthwhile trying to understand exactly why this issue occurs. I find it highly suspicious that this compilation error always occurs with `lens` or `unitTests` -- two packages that were engineered in similar ways...

**Comment by jstolarek** [comment]
We shouldn't close this - the problem still exists (ran into it last week) and hasn't been fixed.

**Comment by jamescheney** [comment]
A similar problem happens after doing `opam switch` to move from one OCaml version to another.  For example if I have Links built using 4.07 and then switch to 4.08 and do "make" I get:
```
File "lens/lens_list.ml", line 1:
Error: lens/.links_lens.objs/byte/links_lens.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
File "lens/column.ml", line 1:
Error: lens/.links_lens.objs/byte/links_lens__Type.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
File "lens/phrase_typesugar.ml", line 1:
Error: lens/.links_lens.objs/byte/links_lens__Value.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
File "lens/phrase.ml", line 1:
Error: I/O error: lens/.links_lens.objs/byte/links_lens__Value.cmi: No such file or directory
File "lens/sorted_records.ml", line 1:
Error: I/O error: lens/.links_lens.objs/byte/links_lens__Value.cmi: No such file or directory
File "lens/eval_classic.ml", line 1:
Error: lens/.links_lens.objs/byte/links_lens.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
File "lens/eval_incremental.ml", line 1:
Error: lens/.links_lens.objs/byte/links_lens.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
```
This suggests that `dune` is correctly detecting that compiled code needs to be regenerated for most things but not for these specific lens-related things.  Perhaps fixing this replicable problem will also fix the original one.

It also seems that both these errors and the one reported originally pertain to bytecode-compiled interface files.  It seems that we are generally (trying to) build native code so I am not sure why these are being generated in the first place.  Perhaps inconsistent settings regarding whether native code or bytecode should be compiled are responsible for this problem.

**Comment by rudihorn** [comment]
So I did a little debugging and as far as I can tell these problems go away when the line

```
          -annot              ;; Dumps information per (file) module about types, bindings, tail-calls, etc. Used by some tools.
```

is removed in the `dune` file in the links directory.

**Comment by frank-emrich** [comment]
@rudihorn 
> So I did a little debugging and as far as I can tell these problems go away when the line `-anot ...`  is removed in the dune file in the links directory.

This would break merlin (which I suspect many of us use), for instance preventing you from querying for the type of an expression or going to a definition in emacs.

Removing non-standard or experimental build flags sounds like a good idea, though.

**Comment by dhil** [comment]
Indeed the option `-annot` causes the compiler to dump meta information used by tools such as Merlin.

Setting `implicit_transitive_deps` to `false` requires us to list all dependencies explicitly in the configuration files. I am not sure what "non-standard" or "experimental" compiler options you are referring to.

**Comment by rudihorn** [comment]
There are three emacs plugins for Ocaml development. Merlin performs autocompletion and does not use them. Tuareg and caml-mode provide "ocaml modes", but Tuareg does not depend on *.annot files and the Tuareg docs mention:

> caml-mode (available in MELPA) is used to display types (using the obsolete *.annot files), open a module for documentation,...

I'm not even sure Caml-mode still uses the annot files as they are not mentioned, but the project seems more legacy in any case.

Either way I don't notice a thing with my autocompletion based on Tuareg and Merlin and I recommend you try to see if anything actually breaks.

**Comment by dhil** [comment]
> Either way I don't notice a thing not working with my autocompletion based on Tuareg and Merlin without -annot and I recommend you try to see if anything actually breaks.

You may be right! A bit confusingly, it seems we ought to use `-bin-annot` instead! After reading the documentation I understand that the `-annot` exists mainly for legacy reasons. It produces `.annot` files. The `-bin-annot` populates the `.cmt` files with meta information, and I believe those are the files used by merlin & co.

**Comment by rudihorn** [comment]
> it seems we ought to use `-bin-annot`

In the current state things just work. It seems the `*.cmt` files are already built automatically. So there is no need to add a flag, which might well cause the same or other issues either now or another day.

**Comment by rudihorn** [comment]
It seems this is also hard-coded into dune: https://github.com/ocaml/dune/blob/master/src/dune/module_compilation.ml#L119-L123

**Comment by dhil** [comment]
> It seems this is also hard-coded into dune: https://github.com/ocaml/dune/blob/master/src/dune/module_compilation.ml#L119-L123

This certainly seems to explain why the `.cmt` files appear "automatically".

**Comment by dhil** [comment]
Please report here if you experience this issue when using patch #905.

**Comment by jamescheney** [comment]
I suggest we leave this open for one month and close it if no one has run into this problem by then.

**Comment by jstolarek** [comment]
I'm still running into this problem and it seems like I can always reproduce it on my side. Preparation steps:
```
git fetch
git checkout -b issue-441 origin/issue-441
git checkout master
git pull
```
And now reproducing the bug:
```
make
git checkout issue-441
make
```
I always get:
```
File "lens/eval_classic.ml", line 1:
Error: The files lens/.links_lens.objs/byte/links_lens__Value.cmi
       and lens/.links_lens.objs/byte/links_lens.cmi
       make inconsistent assumptions over interface Links_lens__Value
File "lens/eval_incremental.ml", line 1:
Error: The files lens/.links_lens.objs/byte/links_lens__Value.cmi
       and lens/.links_lens.objs/byte/links_lens.cmi
       make inconsistent assumptions over interface Links_lens__Value
make: *** [Makefile:102: build-dev-all] Error 1
```

**Comment by rudihorn** [comment]
Yes of course that will throw an error. You are compiling the version with the fix, then switching to the version without the fix and trying to compile it. If you push a commit to `issue-441` removing `-annot` it will work again. The more important direction of compiling `issue-441` and then compiling `master` works just fine.

**Comment by jstolarek** [comment]
Ah, good point - didn't realize the branch isn't rebased on the fix.

**Comment by jamescheney** [comment]
> I suggest we leave this open for one month and close it if no one has run into this problem by then.

It is now more than one month since I wrote this and there haven't been any further occurrences of this issue (excluding Janek's comment above which occurred in a branch that hadn't been fixed yet).  Closing.
